services:
  db:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PLANNER_DATABASE_USER}
      POSTGRES_DB: ${PLANNER_DATABASE_NAME}
      POSTGRES_PASSWORD: ${PLANNER_DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
  mailpit:
    driver: local